[package]
name = "desktop_emul8tor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu_core = { path = "../core" }
sdl2 = "0.35.2"
